[default]
parser = "@comet-cli/parser-open-api"

[commands.make.schemas]
decorators = ["@comet-cli/decorator-json-schemas"]
factories = ["@comet-cli/factory-json-schemas"]
output = "exports/schemas"

[commands.make.tests]
decorators = ["@comet-cli/decorator-json-schemas", "@comet-cli/decorator-tests"]
factories = ["@comet-cli/factory-tests-laravel"]
output = "tests/Comet123"
base_url = "/api" # Base url to which the endpoints get appended.
